# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user1 = User.create(username: "martin", password: "martinU", full_name: "Martin Urrutia", email: "martin@gmail.com", age: 21)
user2 = User.create(username: "juan", password: "juanan", full_name: "Juan Antonio", email: "juan@gmail.com", age: 23)
user3 = User.create(username: "julia", password: "flor", full_name: "Julia Sanchez", email: "julia@gmail.com", age: 22)
user4 = User.create(username: "julio", password: "july", full_name: "Julio Perez", email: "julio@gmail.com", age: 16)
user5 = User.create(username: "pepe", password: "tenedor", full_name: "Pepe Gonzalez", email: "pepe1@gmail.com", age: 44)
user6 = User.create(username: "pepe2", password: "cuchara", full_name: "Pepe Perez", email: "pepe2@gmail.com", age: 32)
user7 = User.create(username: "pepe3", password: "tetera", full_name: "Pepe Fernandez", email: "pepe3@gmail.com", age: 18)
user8 = User.create(username: "Tulio", password: "cleo", full_name: "Tulio Jimenez", email: "tulio@gmail.com", age: 21)
user9 = User.create(username: "Rosa", password: "olla", full_name: "Rosa Diaz", email: "rosa@gmail.com", age: 30)
user10 = User.create(username: "lola", password: "alola", full_name: "Paola Gutierrez", email: "paola@gmail.com", age: 17)

organization1 = Organization.create(name: "WebTech",description: "Only for students")
organization2 = Organization.create(name: "Neighbors board",description: "For neighborhood residents")
organization3 = Organization.create(name: "ONU",description: "United Nations Organization")
organization4 = Organization.create(name: "UANDES",description: "Universidad de los Andes")
organization5 = Organization.create(name: "Race",description: "All about racing")

event1 = Event.create(name: "Exam", description: "The last exam", location: "home", creation_date: 2020-7-1, starting_event_date: 2020-7-11, event_privacy: 1, user: user1)
event2 = Event.create(name: "Party", description: "Zoom party", location: "everywhere", creation_date: 2020-2-3, starting_event_date: 2020-8-9, event_privacy: 0, user: user2)
event3 = Event.create(name: "Speech", description: "Speech about make peace", location: "Santiago", creation_date: 2020-06-11, starting_event_date: 2021-1-03, event_privacy: 0, user: user4)
event4 = Event.create(name: "Concert", description: "Of the orchestra", location: "sydney opera house", creation_date: 2020-3-1, starting_event_date: 2021-3-24, event_privacy: 0, user: user3)
event5 = Event.create(name: "Race", description: "The final", location: "Viña del mar", creation_date: 2020-12-1, starting_event_date: 2021-4-13, event_privacy: 1, user: user1)



organization1.events << event1
organization2.events << event2
organization3.events << event3
organization2.events << event4
organization1.events << event5

useronorg1 = UserOnOrganization.create(user_role: 0, user: user1, organization: organization1)
useronorg2 = UserOnOrganization.create(user_role: 1, user: user1, organization: organization2)
useronorg3 = UserOnOrganization.create(user_role: 0, user: user2, organization: organization2)
useronorg4 = UserOnOrganization.create(user_role: 1, user: user2, organization: organization3)
useronorg5 = UserOnOrganization.create(user_role: 1, user: user3, organization: organization1)
useronorg6 = UserOnOrganization.create(user_role: 0, user: user3, organization: organization3)
useronorg7 = UserOnOrganization.create(user_role: 0, user: user4, organization: organization3)
useronorg8 = UserOnOrganization.create(user_role: 1, user: user4, organization: organization1)
useronorg9 = UserOnOrganization.create(user_role: 0, user: user5, organization: organization1)
useronorg10 = UserOnOrganization.create(user_role: 0, user: user5, organization: organization3)
useronorg12 = UserOnOrganization.create(user_role: 0, user: user6, organization: organization2)
useronorg13 = UserOnOrganization.create(user_role: 0, user: user6, organization: organization4)
useronorg14 = UserOnOrganization.create(user_role: 1, user: user6, organization: organization5)
useronorg15 = UserOnOrganization.create(user_role: 0, user: user7, organization: organization4)
useronorg16 = UserOnOrganization.create(user_role: 0, user: user7, organization: organization5)
useronorg18 = UserOnOrganization.create(user_role: 0, user: user8, organization: organization4)
useronorg19 = UserOnOrganization.create(user_role: 0, user: user8, organization: organization5)
useronorg21 = UserOnOrganization.create(user_role: 0, user: user9, organization: organization4)
useronorg22 = UserOnOrganization.create(user_role: 0, user: user9, organization: organization5)
useronorg24 = UserOnOrganization.create(user_role: 0, user: user10, organization: organization4)
useronorg25 = UserOnOrganization.create(user_role: 0, user: user10, organization: organization5)

systemadmin = SystemAdministrator.create(is_admin: 1, user: user1)
systemadmin = SystemAdministrator.create(is_admin: 1, user: user2)
systemadmin = SystemAdministrator.create(is_admin: 0, user: user3)
systemadmin = SystemAdministrator.create(is_admin: 0, user: user4)
systemadmin = SystemAdministrator.create(is_admin: 1, user: user5)
systemadmin = SystemAdministrator.create(is_admin: 0, user: user6)
systemadmin = SystemAdministrator.create(is_admin: 1, user: user7)
systemadmin = SystemAdministrator.create(is_admin: 0, user: user8)
systemadmin = SystemAdministrator.create(is_admin: 1, user: user9)
systemadmin = SystemAdministrator.create(is_admin: 0, user: user10)

useronevent1 = UserOnEvent.create(status: 0, event: event1, user: user1)
useronevent2 = UserOnEvent.create(status: 0, event: event1, user: user2)
useronevent3 = UserOnEvent.create(status: 1, event: event2, user: user2)
useronevent4 = UserOnEvent.create(status: 1, event: event2, user: user3)
useronevent5 = UserOnEvent.create(status: 2, event: event3, user: user4)
useronevent6 = UserOnEvent.create(status: 2, event: event3, user: user1)
useronevent7 = UserOnEvent.create(status: 2, event: event4, user: user3)
useronevent8 = UserOnEvent.create(status: 1, event: event4, user: user2)
useronevent9 = UserOnEvent.create(status: 0, event: event4, user: user4)

vote1 = DateVote.create(event: event1, user: user1,date_voted: 2020-3-4)
vote2 = DateVote.create(event: event1, user: user2,date_voted: 2020-5-5)
vote3 = DateVote.create(event: event2, user: user2,date_voted: 2020-1-1)
vote4 = DateVote.create(event: event2, user: user3,date_voted: 2020-6-2)
vote5 = DateVote.create(event: event3, user: user4,date_voted: 2020-12-2)
vote6 = DateVote.create(event: event3, user: user1,date_voted: 2020-3-12)
vote7 = DateVote.create(event: event4, user: user3,date_voted: 2020-8-11)
vote8 = DateVote.create(event: event4, user: user2,date_voted: 2020-10-6)
vote9 = DateVote.create(event: event5, user: user5,date_voted: 2020-4-3)
vote13 = DateVote.create(event: event5, user: user9,date_voted: 2020-12-6)
vote14 = DateVote.create(event: event5, user: user10,date_voted: 2020-7-10)

comment1 = Comment.create(message: "Oh no, I hate exams",event: event1, user: user1)
comment2 = Comment.create(message: "Oh yeah a party",event: event2, user: user2)
comment3 = Comment.create(message: "I will see it",event: event3, user: user3)
comment4 = Comment.create(message: "Boring",event: event4, user: user4)
comment5 = Comment.create(message: "Hope it doesnt postpone more",event: event1, user: user3)
comment6 = Comment.create(message: "I got beer",event: event2, user: user1)
comment7 = Comment.create(message: "We need peace",event: event3, user: user4)
comment8 = Comment.create(message: "I love it",event: event4, user: user2)
comment9 = Comment.create(message: "I will go with my father",event: event5, user: user5)
comment13 = Comment.create(message: "OMG",event: event5, user: user9)
comment17 = Comment.create(message: "im going to sneak into",event: event5, user: user7)
comment19 = Comment.create(message: "Wow, I can wait",event: event5, user: user10)

reply1 = CommentReply.create(message: "it's easy if you study",comment: comment1, user: user2)
reply2 = CommentReply.create(message: "it is a zoom party",comment: comment2, user: user3)
reply3 = CommentReply.create(message: "me too",comment: comment3, user: user4)
reply4= CommentReply.create(message: "you are boring",comment: comment4, user: user2)
reply5 = CommentReply.create(message: "mee too!!",comment: comment5, user: user3)
reply6 = CommentReply.create(message: "Send me one",comment: comment6, user: user4)
reply7 = CommentReply.create(message: "it's true",comment: comment7, user: user2)
reply8 = CommentReply.create(message: "me too",comment: comment9, user: user5)
reply13 = CommentReply.create(message: "neither do I",comment: comment19, user: user10)
reply14 = CommentReply.create(message: "calling the police",comment: comment17, user: user5)
